# -*- coding: utf-8 -*-
"""proj-Medical_insurance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uzeMPCR66GbPx_92yVvFijp66yNM7yQ-
"""

import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.preprocessing import PolynomialFeatures
from sklearn.svm import SVR

"""Data importing and Analysis"""

data=pd.read_csv('/content/insurance.csv')

data.shape

data.head()

data.describe()

data.isnull().sum()

data['smoker'].value_counts()

data['sex'].value_counts()

data['region'].value_counts()

data.replace({'sex':{'male':0,'female':1}},inplace=True)

# Assuming df is your DataFrame
correlation_matrix = data.corr()['charges']
print(correlation_matrix)

data.replace({'smoker':{'yes':1,'no':0}},inplace=True)
data.replace({'region':{'southeast':0,'southwest':1,'northwest':2,
'northeast':3}},inplace=True)

data.head()

x=data.drop(['charges'],axis=1)

y=data['charges']

print(x)
x.head()

print(y)
y.head()

"""**train test splits::**"""

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

x_train.shape

x_test.shape
y_train.shape
y_test.shape

"""Training and choosing algorithm for ml modellll:"""

model=Lasso()

model.fit(x_train,y_train)



predict=model.predict(x_train)
# predict.shape
mean_error=metrics.r2_score(y_train,predict)

print(mean_error)

predict=model.predict(x_test)
mean_error=metrics.r2_score(y_test,predict)
print(mean_error)

import numpy as np

input=(62,1,26.25,0,1,0)
input_numpy=np.asarray(input)
input_reshape=input_numpy.reshape(1,-1)
predicted_cost=model.predict(input_reshape)
print(predicted_cost)

print(x)

print(y)

